unstable_features = true
indent_style = "Block" # "Block"
imports_granularity = "Crate" # "Preserve"
comment_width = 100
wrap_comments = true
trailing_comma = "Vertical"
max_width = 100 # 100
blank_lines_lower_bound = 0
control_brace_style = "ClosingNextLine" # "AlwaysSameLine"
#control_brace_style = "AlwaysSameLine"
license_template_path = "" # ""
merge_derives = true # true
overflow_delimited_expr = true # false
# Stable
reorder_modules = true
reorder_imports = true # true
tab_spaces = 4 # 4
use_field_init_shorthand = true # false
use_small_heuristics = "Max" # "Default"
struct_lit_width = 50 # 18
single_line_if_else_max_width = 50 # 50
# Not stable
reorder_impl_items = true # false
where_single_line = true # false 
trailing_semicolon = true
binop_separator = "Front"
empty_item_single_line = true # true
fn_single_line = true # false
format_strings = true # false
struct_lit_single_line = true # true
struct_field_align_threshold = 20 # 0

